import sys, argparse
from pathlib import Path
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

def load_data(path: Path):
    if not path.exists():
        idx = pd.date_range(end=pd.Timestamp.utcnow(), periods=400, freq="T")
        prices = 100 + np.cumsum(np.random.randn(len(idx))) * 0.1
        df = pd.DataFrame({
            "timestamp": idx,
            "open": prices,
            "high": prices * 1.001,
            "low": prices * 0.999,
            "close": prices
        })
        df = df.set_index("timestamp")
        return df
    df = pd.read_csv(path, parse_dates=["timestamp"])
    return df.sort_values("timestamp").set_index("timestamp")

def make_plot(df, out_png: Path):
    plt.figure(figsize=(10,4))
    plt.plot(df.index, df["close"], lw=1.2, color="tab:blue")
    if "low" in df.columns and "high" in df.columns:
        plt.fill_between(df.index, df["low"], df["high"], color="tab:blue", alpha=0.08)
    plt.title("Backtest price (close)")
    plt.xlabel("time")
    plt.ylabel("price")
    plt.grid(alpha=0.3)
    plt.tight_layout()
    out_png.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out_png, dpi=150)
    plt.close()

def write_html(png_name: str, out_html: Path):
    html = f"""<!doctype html>
<html>
  <head><meta charset="utf-8"><title>Backtest result</title></head>
  <body>
    <h1>Backtest result</h1>
    <p>Generated by tools/run_backtest.py</p>
    <img src="{png_name}" alt="backtest plot" style="max-width:100%;height:auto;" />
  </body>
</html>"""
    out_html.write_text(html, encoding="utf-8")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="bt_plot.html")
    parser.add_argument("--data", default="data/ohlc.csv")
    args = parser.parse_args()

    out_html = Path(args.output)
    out_png = out_html.with_suffix(".png")
    df = load_data(Path(args.data))
    make_plot(df, out_png)
    write_html(out_png.name, out_html)
    print("Wrote", out_html, "and", out_png)

if __name__ == "__main__":
    main()
